is_train: True
ddp: False
stat: ts
root_path: /
project: s2g
data_path:  ./data/datasets/beats2/PantoMatrix/EMAGE/test_sequences/
data_path_1:  ./data/datasets/beats2/PantoMatrix/EMAGE/


# data config
training_speakers: [2] #[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
additional_data: False
cache_path:  ./data/datasets/beats2/PantoMatrix/datasets/beat_cache/beat_smplx_en_emage_test/
dataset: beat_testonly
new_cache: False

# motion config
ori_joints: beat_smplx_joints
tar_joints: beat_smplx_full
pose_rep: smplxflame_30
pose_norm: False
pose_fps: 30
rot6d: True
pre_frames: 4
pose_dims: 330
pose_length: 64
stride: 20
test_length: 64
motion_f: 256
m_pre_encoder: null
m_encoder: null
m_fix_pre: False

# audio config
audio_rep: onset+amplitude
audio_sr: 16000
audio_fps: 16000
audio_norm: False
audio_f: 256
# a_pre_encoder: tcn_camn
# a_encoder: none
# a_fix_pre: False

# text config
word_rep: textgrid
word_index_num: 11195
word_dims: 300
freeze_wordembed: False
word_f: 256
t_pre_encoder: fasttext
t_encoder: null
t_fix_pre: False

# facial config
facial_rep: smplxflame_30
facial_dims: 100
facial_norm: False
facial_f: 0
f_pre_encoder: null
f_encoder: null
f_fix_pre: False

# speaker config
id_rep: onehot
speaker_f: 0


# motioncraft adding for support
multi_length_training: [1.0]
beat_align: True
word_cache: False
disable_filtering: False
clean_first_seconds: 0
clean_final_seconds: 0
emo_rep: null
sem_rep: null
loader_workers: 0

debug: False
render_video_fps: 30
render_video_width: 1920
render_video_height: 720
render_concurrent_num: 16
render_tmp_img_filetype: "bmp"